### ISSUE TITLE
Documentation doesn't work in neovim

### ISSUE THREAD

**Issue by spwx** [gu-fan/riv.vim#121]
Hello! And thank you for such a great plugin!

I am having a hard time accessing Riv's documentation in neovim.

:RivQuickStart doesn't do anything and none of the links in :h riv work.

I'd appreciate any help!

**Comment by gu-fan** [comment]
nope... I'm not using neovim......

**Comment by gu-fan** [comment]
use https://github.com/gu-fan/riv.vim/blob/master/doc/riv_quickstart.rst

**Comment by dsem** [comment]
I can replicate this with neovim. The documentation works if you open a `nvim` without a file, but if you have a file in the buffer, then the commands do nothing.

**Comment by farisachugthai** [comment]
Well the tags file in the docs dir is about 200 bytes for me. @gu-fan if you're not having this issue how are you creating your docs? `vim -c 'helptags .'` or ctags or exuberant tags?

Because in both neovim and vim I have no functional documentation, but I would take a guess that the fact that I have no tags except for the 5 in the riv.txt file is the causing factor.

@dsem @spwx can you guys check your tags files?
